# Generated by Django 3.1 on 2021-09-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210527_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='average_sentiment',
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_tweets_neg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_tweets_pos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='top_tweets_neg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='top_tweets_pos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
